import React, { useEffect, useState, useMemo } from 'react'
import type { Signal } from '../types/api'
import { useApi } from '../hooks/useApi'
import useAppStore from '../store/appStore'
import { Card } from '../components/Common/Card'
import { ChevronDown, Download, Filter } from 'lucide-react'

export default function SignalsPage() {
  const [apiSignals, setApiSignals] = useState<Signal[]>([])
  const [filteredSignals, setFilteredSignals] = useState<Signal[]>([])
  const [loading, setLoading] = useState(true)
  const [filterStatus, setFilterStatus] = useState('ALL')
  const [filterSymbol, setFilterSymbol] = useState('ALL')
  const [page, setPage] = useState(1)
  const itemsPerPage = 20
  const { get } = useApi()
  
  // Get realtime signals from WebSocket store
  const realtimeSignals = useAppStore(state => state.signals)
  
  // Merge API signals with realtime signals (realtime takes priority)
  const signals = useMemo(() => {
    const apiSignalIds = new Set(apiSignals.map(s => s.id))
    const newRealtimeSignals = realtimeSignals.filter(s => !apiSignalIds.has(s.id))
    return [...newRealtimeSignals, ...apiSignals]
  }, [apiSignals, realtimeSignals])

  useEffect(() => {
    const fetchSignals = async () => {
      try {
        const response = await get('/api/v1/signals?limit=500')
        setApiSignals(response.data)
        setLoading(false)
      } catch (error) {
        console.error('Failed to fetch signals:', error)
        setLoading(false)
      }
    }

    fetchSignals()
    const interval = setInterval(fetchSignals, 30000)
    return () => clearInterval(interval)
  }, [])

  useEffect(() => {
    let filtered = signals

    if (filterStatus !== 'ALL') {
      filtered = filtered.filter(s => s.status === filterStatus)
    }

    if (filterSymbol !== 'ALL') {
      filtered = filtered.filter(s => s.symbol === filterSymbol)
    }

    setFilteredSignals(filtered)
    setPage(1)
  }, [signals, filterStatus, filterSymbol])

  const symbols = [...new Set(signals.map(s => s.symbol))]
  const statuses = ['ACTIVE', 'TP_HIT', 'SL_HIT', 'CANCELLED', 'BREAKEVEN']

  const paginatedSignals = filteredSignals.slice(
    (page - 1) * itemsPerPage,
    page * itemsPerPage
  )
  const totalPages = Math.ceil(filteredSignals.length / itemsPerPage)

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'ACTIVE':
        return 'bg-blue-900/30 text-blue-400 border-blue-700'
      case 'TP_HIT':
        return 'bg-green-900/30 text-green-400 border-green-700'
      case 'SL_HIT':
        return 'bg-red-900/30 text-red-400 border-red-700'
      case 'CANCELLED':
        return 'bg-gray-700/30 text-gray-400 border-gray-600'
      default:
        return 'bg-yellow-900/30 text-yellow-400 border-yellow-700'
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-white mb-2">Signals History</h1>
        <p className="text-gray-400">All trading signals generated by the bot</p>
      </div>

      {/* Filters */}
      <Card title="Filters">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="text-sm text-gray-400 block mb-2">Status</label>
            <select
              value={filterStatus}
              onChange={e => setFilterStatus(e.target.value)}
              className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded text-white text-sm focus:outline-none focus:border-green-500"
            >
              <option value="ALL">All Statuses</option>
              {statuses.map(status => (
                <option key={status} value={status}>
                  {status}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="text-sm text-gray-400 block mb-2">Symbol</label>
            <select
              value={filterSymbol}
              onChange={e => setFilterSymbol(e.target.value)}
              className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded text-white text-sm focus:outline-none focus:border-green-500"
            >
              <option value="ALL">All Symbols</option>
              {symbols.map(symbol => (
                <option key={symbol} value={symbol}>
                  {symbol}
                </option>
              ))}
            </select>
          </div>

          <div className="flex items-end gap-2">
            <button className="flex-1 px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded transition flex items-center justify-center gap-2">
              <Filter className="w-4 h-4" />
              Apply
            </button>
            <button className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded transition flex items-center gap-2">
              <Download className="w-4 h-4" />
              Export
            </button>
          </div>
        </div>
      </Card>

      {/* Table */}
      <Card title={`Signals (${filteredSignals.length} total)`}>
        {loading ? (
          <div className="text-center py-8 text-gray-400">Loading signals...</div>
        ) : (
          <>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-gray-700">
                    <th className="text-left py-3 px-3 font-semibold text-gray-300">Symbol</th>
                    <th className="text-left py-3 px-3 font-semibold text-gray-300">Type</th>
                    <th className="text-right py-3 px-3 font-semibold text-gray-300">Entry</th>
                    <th className="text-right py-3 px-3 font-semibold text-gray-300">SL</th>
                    <th className="text-right py-3 px-3 font-semibold text-gray-300">TP</th>
                    <th className="text-right py-3 px-3 font-semibold text-gray-300">Qty</th>
                    <th className="text-center py-3 px-3 font-semibold text-gray-300">Status</th>
                    <th className="text-right py-3 px-3 font-semibold text-gray-300">R:R</th>
                    <th className="text-left py-3 px-3 font-semibold text-gray-300">Time</th>
                  </tr>
                </thead>
                <tbody>
                  {paginatedSignals.map(signal => (
                    <tr
                      key={signal.id}
                      className="border-b border-gray-700 hover:bg-gray-800/50 transition cursor-pointer"
                    >
                      <td className="py-3 px-3 font-bold text-white">{signal.symbol}</td>
                      <td className="py-3 px-3">
                        <span
                          className={`text-xs px-2 py-1 rounded ${
                            signal.signal_type === 'BUY'
                              ? 'bg-green-900/30 text-green-400'
                              : 'bg-red-900/30 text-red-400'
                          }`}
                        >
                          {signal.signal_type}
                        </span>
                      </td>
                      <td className="py-3 px-3 text-right font-mono text-white">
                        {signal.entry.toLocaleString()}
                      </td>
                      <td className="py-3 px-3 text-right font-mono text-red-400">
                        {signal.stop_loss.toLocaleString()}
                      </td>
                      <td className="py-3 px-3 text-right font-mono text-green-400">
                        {signal.take_profit.toLocaleString()}
                      </td>
                      <td className="py-3 px-3 text-right text-gray-300">{signal.quantity}</td>
                      <td className="py-3 px-3 text-center">
                        <span className={`text-xs px-2 py-1 rounded border ${getStatusColor(signal.status)}`}>
                          {signal.status}
                        </span>
                      </td>
                      <td className="py-3 px-3 text-right font-bold text-yellow-400">
                        {signal.risk_reward_ratio}x
                      </td>
                      <td className="py-3 px-3 text-xs text-gray-400">
                        {new Date(signal.timestamp).toLocaleString()}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Pagination */}
            <div className="mt-4 flex items-center justify-between">
              <div className="text-sm text-gray-400">
                Showing {(page - 1) * itemsPerPage + 1} to {Math.min(page * itemsPerPage, filteredSignals.length)} of{' '}
                {filteredSignals.length}
              </div>
              <div className="flex gap-2">
                <button
                  onClick={() => setPage(p => Math.max(1, p - 1))}
                  disabled={page === 1}
                  className="px-3 py-1 bg-gray-700 text-gray-300 rounded disabled:opacity-50"
                >
                  Prev
                </button>
                {Array.from({ length: totalPages }, (_, i) => i + 1)
                  .slice(Math.max(0, page - 2), Math.min(totalPages, page + 1))
                  .map(p => (
                    <button
                      key={p}
                      onClick={() => setPage(p)}
                      className={`px-3 py-1 rounded transition ${
                        p === page
                          ? 'bg-green-600 text-white'
                          : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
                      }`}
                    >
                      {p}
                    </button>
                  ))}
                <button
                  onClick={() => setPage(p => Math.min(totalPages, p + 1))}
                  disabled={page === totalPages}
                  className="px-3 py-1 bg-gray-700 text-gray-300 rounded disabled:opacity-50"
                >
                  Next
                </button>
              </div>
            </div>
          </>
        )}
      </Card>
    </div>
  )
}
